// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHscNe7v9QJinngMSPfW8fPDydHlwICI',
    appId: '1:807829589402:web:efbf4a868fdbc4c449fe23',
    messagingSenderId: '807829589402',
    projectId: 'furniture-renting-91dac',
    authDomain: 'furniture-renting-91dac.firebaseapp.com',
    databaseURL: 'https://furniture-renting-91dac-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-renting-91dac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreB1zWGExyp-bDr3irnSFyea-XrD7LIE',
    appId: '1:807829589402:android:f0f0f16db6fe173949fe23',
    messagingSenderId: '807829589402',
    projectId: 'furniture-renting-91dac',
    databaseURL: 'https://furniture-renting-91dac-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-renting-91dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDXSCwsbV-WUbb4A77XV5GOCuagWQ6jw',
    appId: '1:807829589402:ios:22abc86ef9e0be6749fe23',
    messagingSenderId: '807829589402',
    projectId: 'furniture-renting-91dac',
    databaseURL: 'https://furniture-renting-91dac-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-renting-91dac.appspot.com',
    iosBundleId: 'com.example.clothing',
  );
}
